enum FrontDeskRouteNames {
  FD_ROOT_NAVIGATION = 'FD_ROOT_NAVIGATION',
  FD_BOTTOM_TAB = 'FD_BOTTOM_TAB',
  FD_APPOINTMENTS = 'FD_APPOINTMENTS',
  FD_CREATE_INVOICE = 'FD_CREATE_INVOICE',
  FD_PAY_INVOICE = 'FD_PAY_INVOICE',
  FD_CALENDAR = 'FD_CALENDAR',
  FD_ADD_NEW_PATIENT = 'FD_ADD_NEW_PATIENT',
  FD_ADD_NEW_APPOINTMENT = 'FD_ADD_NEW_APPOINTMENT',
  FD_EDIT_APPOINTMENT = 'FD_EDIT_APPOINTMENT',
  FD_VIEW_APPOINTMENT_INFO = 'FD_VIEW_APPOINTMENT_INFO',
  FD_SCAN_PAPER_RECORDS = 'FD_SCAN_PAPER_RECORDS',
  FD_PATIENT_PROFILE = 'FD_PATIENT_PROFILE',
  FD_PATIENT_OVERVIEW = 'FD_PATIENT_OVERVIEW',
  FD_REVIEW_DETAILED_HISTORY = 'FD_REVIEW_DETAILED_HISTORY',
  FD_PAYMENT_CONFIRMATION = 'FD_PAYMENT_CONFIRMATION',
  FD_WARD_ROUND_AND_CLINIC_NOTES = 'FD_WARD_ROUND_AND_CLINIC_NOTES',
  FD_VIEW_REFERRAL_LETTER = 'FD_VIEW_REFERRAL_LETTER',
  FD_ADD_DEMOGRAPHIC_INFO = 'FD_ADD_DEMOGRAPHIC_INFO',
}

enum DoctorRouteNames {
  DOCTOR_ROOT_NAVIGATION = 'DOCTOR_ROOT_NAVIGATION',
  DOCTOR_BOTTOM_TAB = 'DOCTOR_BOTTOM_TAB',
  DOCTOR_PATIENTS = 'DOCTOR_PATIENTS',
  DOCTOR_ALL_PATIENTS = 'DOCTOR_ALL_PATIENTS',
  DOCTOR_ALL_INPUTS = 'DOCTOR_ALL_INPUTS',
  DOCTOR_DIAGNOSIS = 'DOCTOR_DIAGNOSIS',
  DOCTOR_PRESENTING_COMPLAINTS = 'DOCTOR_PRESENTING_COMPLAINTS',
  DOCTOR_PRESCRIPTIONS = 'DOCTOR_PRESCRIPTIONS',
  DOCTOR_PROCEDURES = 'DOCTOR_PROCEDURES',
  DOCTOR_INVESTIGATIONS = 'DOCTOR_INVESTIGATIONS',
}

enum NurseRouteNames {
  NURSE_ROOT_NAVIGATION = 'NURSE_ROOT_NAVIGATION',
  NURSE_BOTTOM_TAB = 'NURSE_BOTTOM_TAB',
  NURSE_PATIENTS = 'NURSE_PATIENTS',
  NURSE_AUTO_ASSIGN = 'NURSE_AUTO_ASSIGN',
  NURSING_CARE_PLAN = 'NURSING_CARE_PLAN',
  NURSE_MISCELLANEOUS_INTERVENTIONS = 'NURSE_MISCELLANEOUS_INTERVENTIONS',
  NURSE_BED_MAKING = 'NURSE_BED_MAKING',
  NURSE_WOUND_DRESSING = 'NURSE_WOUND_DRESSING',
  NURSE_INTAKE_OUTPUT_CHARTING = 'NURSE_INTAKE_OUTPUT_CHARTING',
  NURSE_MEDICATION = 'NURSE_MEDICATION',
  OUT_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD = 'OUT_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD',
  IN_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD = 'IN_PATIENT_NURSE_ALL_INPUT_LANDING_DASHBOARD',
}

type RouteNames = {
  AUTH_STACK: 'AUTH_STACK';
  LOGIN: 'LOGIN';
  RESET_PASSWORD: 'RESET_PASSWORD';
  ENTER_OTP: 'ENTER_OTP';
  CREATE_NEW_PASSWORD: 'CREATE_NEW_PASSWORD';
  FRONT_DESK: typeof FrontDeskRouteNames;
  DOCTOR: typeof DoctorRouteNames;
  NURSE: typeof NurseRouteNames;
  VIEW_PARER_RECORDS_TAB: 'VIEW_PARER_RECORDS_TAB';
  ADD_NOTES: 'ADD_NOTES';
  VITAL_SIGNS: 'VITAL_SIGNS';
  INVESTIGATIONS: 'INVESTIGATIONS';
  PHYSICAL_EXAMINATION: 'PHYSICAL_EXAMINATION';
  OTHER_PLAN_ITEMS: 'OTHER_PLAN_ITEMS';
  USER_PROFILE: 'USER_PROFILE';
  EDIT_USER_PROFILE: 'EDIT_USER_PROFILE';
  NOTIFICATIONS: 'NOTIFICATIONS';
  MESSAGES: 'MESSAGES';
};

export const routesNames: RouteNames = {
  AUTH_STACK: 'AUTH_STACK',
  LOGIN: 'LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  ENTER_OTP: 'ENTER_OTP',
  CREATE_NEW_PASSWORD: 'CREATE_NEW_PASSWORD',
  FRONT_DESK: FrontDeskRouteNames,
  DOCTOR: DoctorRouteNames,
  NURSE: NurseRouteNames,
  VIEW_PARER_RECORDS_TAB: 'VIEW_PARER_RECORDS_TAB',
  PHYSICAL_EXAMINATION: 'PHYSICAL_EXAMINATION',
  ADD_NOTES: 'ADD_NOTES',
  VITAL_SIGNS: 'VITAL_SIGNS',
  INVESTIGATIONS: 'INVESTIGATIONS',
  OTHER_PLAN_ITEMS: 'OTHER_PLAN_ITEMS',
  USER_PROFILE: 'USER_PROFILE',
  EDIT_USER_PROFILE: 'EDIT_USER_PROFILE',
  NOTIFICATIONS: 'NOTIFICATIONS',
  MESSAGES: 'MESSAGES',
};
